[metadata]
name = moore_animateanyone
version = 0.0.1
description = Moore-AnimateAnyone package
license = MIT

[options]
packages = find:
include_package_data = True

[options.packages.find]
where = .
include =
	animate_anyone*

[options.package_data]
animate_anyone =
	configs/**/*.yaml
	configs/**/*.yml
	configs/**/*.json

[options.entry_points]
console_scripts =
	animate-anyone-pose2vid = animate_anyone.scripts.pose2vid:main
	animate-anyone-lmks2vid = animate_anyone.scripts.lmks2vid:main
